version: '3.8'

networks:
  my-network:


services:
  backend:
    build:
      context: ./backEnd
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - my-network
    ports:
      - "5000:5000"


  frontend:
    build:
      context: ./frontEnd
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - my-network
    ports:
      - "8501:8501"
    depends_on:
      - backend
    links:
      - "backend:backend"
  
  prometheus:
    build:
      context: ./prometheusMonitoring
      dockerfile: Dockerfile
    container_name: prometheus
    networks:
      - my-network
    ports:
      - 9090:9090
    depends_on:
      - backend
    links:
      - "backend:backend"

