name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-22.04
    steps:
     - name: Checkout code
       uses: actions/checkout@v2.5.0

     - name: Login to DockerHub
       run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
     
     - name: Build image and push database
       uses: docker/build-push-action@v3
       with:
         context: ./backEnd
         tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest
         push: ${{ github.ref == 'refs/heads/main' }}
     
     - name: Build image and push httpd
       uses: docker/build-push-action@v3
       with:
         context: ./frontEnd
         tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest         
         push: ${{ github.ref == 'refs/heads/main' }}
